---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: chat-mf-app-psrehp-37166-v3
  description: Sole Application
  namespace: glass
  annotations:
    # backstage.io/kubernetes-label-selector: app.kubernetes.io/name=glass-chat-mf,framework=sole
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=chat-mf-app-psrehp-37166-v3,framework=sole
    jenkins.io/job-full-name: WEB-RUNTIME/EC/glass-chat-mf/CI
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
  tags:
    - sole
    - deu02
    - development
  labels:
    framework: sole
    odp_cluster: deu02
    odp_envirnment: development
spec:
  type: service
  lifecycle: experimental
  owner: exp-core
  system: sole-mf
