---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ec-dotcom-techradar-dotcom-techradar-core
  namespace: glass
  annotations:
    # backstage.io/kubernetes-label-selector: app.kubernetes.io/name=ec-dotcom-techradar,framework=sole
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=ec-dotcom-techradar-dotcom-techradar-core,framework=sole
  tags:
    - sole
    - ec-dotcom-techradar
spec:
  type: service
  lifecycle: experimental
  owner: exp-core
