---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ec-mockserver-mockserver-mockserver
  annotations:
    # backstage.io/kubernetes-label-selector: app.kubernetes.io/name=ec-mockserver,framework=sole
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=ec-mockserver-mockserver-mockserver,framework=sole
  tags:
    - sole
    - ec-mockserver
spec:
  type: service
  lifecycle: experimental
  owner: exp-core
