---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: glass-plp-plp-app
  namespace: glass
  annotations:
    # backstage.io/kubernetes-label-selector: app.kubernetes.io/name=glass-plp,framework=sole
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=glass-plp-plp-app,framework=sole
  tags:
    - sole
    - glass-plp
spec:
  type: service
  lifecycle: experimental
  owner: exp-core
