---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: size-charts-api-renovate-npm-10-x
  annotations:
    # backstage.io/kubernetes-label-selector: app.kubernetes.io/name=glass-size-charts-api,framework=sole
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=size-charts-api-renovate-npm-10-x,framework=sole
  tags:
    - sole
    - glass-size-charts-api
spec:
  type: service
  lifecycle: experimental
  owner: exp-core
